# Generated by Django 4.2.7 on 2023-12-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('phone_number', models.BigIntegerField(max_length=17)),
                ('location', models.CharField(max_length=300)),
            ],
        ),
    ]
