# Generated by Django 4.2.7 on 2023-12-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_phone_number_user_phone_number1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('main_phone_number', models.IntegerField()),
                ('additional_phone_number', models.IntegerField()),
                ('location', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
