# Generated by Django 4.2.7 on 2023-12-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customer_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='additional_phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='main_phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
