# Generated by Django 4.2.7 on 2023-12-06 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/categories/%y%m%d')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('amount', models.FloatField(default=0)),
                ('amount_measure', models.CharField(choices=[('kg', 'kg'), ('litr', 'litr'), ('dona', 'dona'), ('metr', 'metr')], default='kg', max_length=25)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to='images/products/%y%m%d')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/subcategories/%y%m%d')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/products/%y%m%d')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.subcategory'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('products_status', models.CharField(choices=[('ALL', 'ALL'), ('CUSTOM', 'CUSTOM')], default='CUSTOM', max_length=25)),
                ('category', models.ManyToManyField(blank=True, related_name='discounts', to='products.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.product')),
                ('products', models.ManyToManyField(blank=True, related_name='discount_many', to='products.product')),
                ('subcategory', models.ManyToManyField(blank=True, related_name='discounts', to='products.subcategory')),
            ],
        ),
    ]
