# Generated by Django 4.2.7 on 2023-11-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_image_alter_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_measure',
            field=models.CharField(choices=[('kg', 'kg'), ('litr', 'litr'), ('dona', 'dona'), ('metr', 'metr')], default='kg', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
